name: MANUAL-BUILD-FORMS

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      # Install NodeJS
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # Setting up registry
      - name: Set registry
        run: npm set @khangroupkz:registry "https://npm.pkg.github.com"
      - run: npm set //npm.pkg.github.com/:_authToken=${{ secrets.GPR_READER_TOKEN }}
      # Install dependencies
      - name: Install dependencies
        run: npm install
      # Export version to step variables
      - name: Export version to step variables
        id: test_version
        run: |
          echo "::set-output name=version::$(jq -r '.version' package.json)"
      # Build
      - name: Build
        run: npm run build --if-present -- --outputPath=dist/ui-v${{ steps.test_version.outputs.version }}
      # Archive build artifacts
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ github.run_number }}-v${{ steps.test_version.outputs.version }}
          path: dist
